export const mouvements = {
  haltero: {
    1: { name: "Power Snatch", unit: "kg", averageQuantity: 15 },
    2: { name: "Squat Snatch", unit: "kg", averageQuantity: 15 },
    3: { name: "Hang Snatch", unit: "kg", averageQuantity: 20 },
    4: { name: "Snatch Balance", unit: "kg", averageQuantity: 25 },
    5: { name: "Clean and Jerk", unit: "kg", averageQuantity: 15 },
    6: { name: "Power Clean", unit: "kg", averageQuantity: 15 },
    7: { name: "Squat Clean", unit: "kg", averageQuantity: 15 },
    8: { name: "Hang Clean", unit: "kg", averageQuantity: 20 },
    // 9: { name: "Split Jerk", unit: "kg", averageQuantity: 20 },
    10: { name: "Push Jerk", unit: "kg", averageQuantity: 65 },
    11: { name: "Push Press", unit: "kg", averageQuantity: 60 },
    12: { name: "Deadlift", unit: "kg", averageQuantity: 100 },
    13: { name: "Sumo Deadlift High Pull", unit: "kg", averageQuantity: 50 },
    14: { name: "Front Squat", unit: "kg", averageQuantity: 15 },
    15: { name: "Overhead Squat", unit: "kg", averageQuantity: 10 },
    16: { name: "Thruster", unit: "kg", averageQuantity: 15 },
  },
  gym: {
    17: { name: "Pull-up", unit: "reps", averageQuantity: 10 },
    18: { name: "Chest-to-Bar", unit: "reps", averageQuantity: 8 },
    19: { name: "Muscle-up", unit: "reps", averageQuantity: 5 },
    20: { name: "Toes-to-Bar", unit: "reps", averageQuantity: 15 },
    21: { name: "Push-up", unit: "reps", averageQuantity: 20 },
    22: { name: "Handstand Push-up", unit: "reps", averageQuantity: 10 },
    23: { name: "Handstand Walk", unit: "meters", averageQuantity: 10 },
    24: { name: "Dip", unit: "reps", averageQuantity: 15 },
    // 25: { name: "L-sit", unit: "seconds", averageQuantity: 30 },
    // 26: { name: "Pistols", unit: "reps", averageQuantity: 10 },
    27: { name: "Ring Dips", unit: "reps", averageQuantity: 10 },
    28: { name: "Ring Muscle-ups", unit: "reps", averageQuantity: 5 },
    29: { name: "Pull-over", unit: "reps", averageQuantity: 10 },
  },
  conditionnement: {
    30: { name: "Run", unit: "meters", averageQuantity: 400 },
    31: { name: "Rowing", unit: "Cal", averageQuantity: 20 },
    32: { name: "Ski Erg", unit: "Cal", averageQuantity: 20 },
    33: { name: "Assault Bike", unit: "Cal", averageQuantity: 20 },
    34: { name: "Echo Bike", unit: "Cal", averageQuantity: 20 },
    35: { name: "Burpees", unit: "reps", averageQuantity: 15 },
    36: { name: "Single-unders", unit: "reps", averageQuantity: 100 },
    37: { name: "Box Jump", unit: "reps", averageQuantity: 20 },
    38: { name: "Wall Ball", unit: "reps", averageQuantity: 20 },
    39: { name: "Kettlebell US Swing", unit: "reps", averageQuantity: 20 },
    40: { name: "Dumbbell Snatch", unit: "reps", averageQuantity: 15 },
    41: { name: "Turkish Get-Up", unit: "reps", averageQuantity: 10 },
    42: { name: "Ball Slam", unit: "reps", averageQuantity: 20 },
    43: { name: "GHD Sit-Up", unit: "reps", averageQuantity: 20 },
    44: { name: "Sled Push", unit: "meters", averageQuantity: 50 },
    45: { name: "Sled Pull", unit: "meters", averageQuantity: 50 },
    46: { name: "Farmer's Carry", unit: "meters", averageQuantity: 100 },
    47: { name: "Sandbag Carry", unit: "meters", averageQuantity: 100 },
    48: { name: "Burpees box jump", unit: "reps", averageQuantity: 15 },
    49: { name: "Burpees box jump over", unit: "reps", averageQuantity: 15 },
    50: { name: "Burpees pull-up", unit: "reps", averageQuantity: 10 },
    51: { name: "Burpees chest-to-bar", unit: "reps", averageQuantity: 8 },
    52: { name: "Burpees Bar muscle-up", unit: "reps", averageQuantity: 5 },
    53: { name: "Burpees ring muscle-up", unit: "reps", averageQuantity: 5 },
    54: { name: "Burpees deadlift", unit: "reps", averageQuantity: 10 },
    55: {
      name: "Burpees barbell facing bar",
      unit: "reps",
      averageQuantity: 15,
    },
    56: { name: "Burpees Broad jump", unit: "reps", averageQuantity: 10 },
    57: { name: "Devil Press", unit: "reps", averageQuantity: 10 },
    57: { name: "Double-unders", unit: "reps", averageQuantity: 50 },
    58: { name: "Cross-over", unit: "reps", averageQuantity: 30 },
    59: { name: "Kettlebell Russian Swing", unit: "reps", averageQuantity: 20 },
    60: { name: "Dumbbell Hang Snatch", unit: "reps", averageQuantity: 15 },
    61: { name: "Dumbbell Clean", unit: "reps", averageQuantity: 15 },
    62: { name: "Dumbbell Hang Clean", unit: "reps", averageQuantity: 15 },
    63: {
      name: "Dumbbell Shoulder to Overhead",
      unit: "reps",
      averageQuantity: 12,
    },
    64: { name: "Dumbbell Clean & Jerk", unit: "reps", averageQuantity: 12 },
    65: { name: "Dumbbell Box Step-up", unit: "reps", averageQuantity: 15 },
    66: { name: "Dumbbell Box over", unit: "reps", averageQuantity: 12 },
  },
};
